import BrickPileLean.BostConnes.FiniteHilbertAdjoint
import Mathlib.Analysis.CStarAlgebra.ContinuousLinearMap
import Mathlib.Topology.Algebra.StarSubalgebra

namespace BrickPileLean
namespace BostConnes

open scoped BigOperators InnerProduct

noncomputable section

/-- Bounded operators on the finite Bost--Connes Hilbert space. -/
abbrev FiniteOperator (S : Finset ℕ) :=
  FiniteHilbertSpace S →L[ℂ] FiniteHilbertSpace S

/-- The exponent vector having exponent one at `p` and zero elsewhere. -/
def primeExponent (S : Finset ℕ) (p : S) : ExponentVector S :=
  fun q => if q = p then 1 else 0

@[simp] theorem semigroupElement_primeExponent (S : Finset ℕ) (p : S) :
    semigroupElement S (primeExponent S p) = p.1 := by
  classical
  unfold semigroupElement primeExponent
  rw [Fintype.prod_eq_single p]
  · simp
  · intro q hqp
    simp [hqp]

/-- The copy of the prime `p ∈ S` inside `Λ_S`. -/
def primeSemigroupElement (S : Finset ℕ) (p : S) : finitePrimeSemigroup S :=
  ⟨p.1, ⟨primeExponent S p, semigroupElement_primeExponent S p⟩⟩

@[simp] theorem primeSemigroupElement_coe (S : Finset ℕ) (p : S) :
    (primeSemigroupElement S p : ℕ) = p.1 :=
  rfl

/-- Every element of `Λ_S` is the product of its prime generators to the corresponding exponents. -/
theorem finitePrimeSemigroup_eq_prod_primePowers
    {S : Finset ℕ} (hS : ∀ p ∈ S, Nat.Prime p)
    (m : finitePrimeSemigroup S) :
    m = ∏ p : S, (primeSemigroupElement S p) ^
      ((exponentVectorEquivFinitePrimeSemigroup S hS).symm m) p := by
  let k := (exponentVectorEquivFinitePrimeSemigroup S hS).symm m
  have hk : exponentVectorEquivFinitePrimeSemigroup S hS k = m :=
    (exponentVectorEquivFinitePrimeSemigroup S hS).apply_symm_apply m
  have hkval : semigroupElement S k = (m : ℕ) := by
    exact congrArg (fun n : finitePrimeSemigroup S => (n : ℕ)) hk
  apply Subtype.ext
  change (m : ℕ) = ∏ p : S, p.1 ^ k p
  rw [← hkval]
  rfl

/-- The identity semigroup element acts as the identity operator. -/
@[simp] theorem shiftOperator_one
    {S : Finset ℕ} (hS : ∀ p ∈ S, Nat.Prime p) :
    shiftOperator hS (1 : finitePrimeSemigroup S) =
      ContinuousLinearMap.id ℂ (FiniteHilbertSpace S) := by
  refine lp.ext_continuousLinearMap (ENNReal.ofNat_ne_top (n := nat_lit 2)) fun n => ?_
  ext z
  simp [shiftOperator]

/-- Multiplication in `Λ_S` is represented by multiplication of shift operators. -/
@[simp] theorem shiftOperator_mul
    {S : Finset ℕ} (hS : ∀ p ∈ S, Nat.Prime p)
    (m n : finitePrimeSemigroup S) :
    shiftOperator hS (m * n) = shiftOperator hS m * shiftOperator hS n := by
  change
    (shiftIsometry hS (m * n)).toContinuousLinearMap =
      (shiftIsometry hS m).toContinuousLinearMap.comp
        (shiftIsometry hS n).toContinuousLinearMap
  exact (shiftIsometry_mul hS m n).symm

/-- The multiplicative representation `m ↦ V_m`. -/
def shiftMonoidHom
    {S : Finset ℕ} (hS : ∀ p ∈ S, Nat.Prime p) :
    finitePrimeSemigroup S →* FiniteOperator S where
  toFun := shiftOperator hS
  map_one' := shiftOperator_one hS
  map_mul' := shiftOperator_mul hS

@[simp] theorem shiftMonoidHom_apply
    {S : Finset ℕ} (hS : ∀ p ∈ S, Nat.Prime p)
    (m : finitePrimeSemigroup S) :
    shiftMonoidHom hS m = shiftOperator hS m :=
  rfl

/-- The set of prime shift generators `V_p`, for `p ∈ S`. -/
def primeShiftSet
    {S : Finset ℕ} (hS : ∀ p ∈ S, Nat.Prime p) : Set (FiniteOperator S) :=
  Set.range fun p : S => shiftOperator hS (primeSemigroupElement S p)

/-- The finite Toeplitz algebra `C*(V_p : p ∈ S)` as a closed star subalgebra of `B(ℓ²(Λ_S))`. -/
def finiteToeplitzAlgebra
    {S : Finset ℕ} (hS : ∀ p ∈ S, Nat.Prime p) :
    StarSubalgebra ℂ (FiniteOperator S) :=
  (StarSubalgebra.adjoin ℂ (primeShiftSet hS)).topologicalClosure

/-- Each prime shift belongs to the finite Toeplitz algebra. -/
theorem primeShift_mem_finiteToeplitzAlgebra
    {S : Finset ℕ} (hS : ∀ p ∈ S, Nat.Prime p) (p : S) :
    shiftOperator hS (primeSemigroupElement S p) ∈ finiteToeplitzAlgebra hS := by
  apply StarSubalgebra.le_topologicalClosure
  exact StarSubalgebra.mem_adjoin_of_mem ⟨p, rfl⟩

/-- Every semigroup shift `V_m` belongs to the algebra generated by the prime shifts. -/
theorem shiftOperator_mem_finiteToeplitzAlgebra
    {S : Finset ℕ} (hS : ∀ p ∈ S, Nat.Prime p)
    (m : finitePrimeSemigroup S) :
    shiftOperator hS m ∈ finiteToeplitzAlgebra hS := by
  let k := (exponentVectorEquivFinitePrimeSemigroup S hS).symm m
  change shiftMonoidHom hS m ∈ finiteToeplitzAlgebra hS
  rw [finitePrimeSemigroup_eq_prod_primePowers hS m, map_prod]
  apply prod_mem
  intro p hp
  rw [map_pow]
  exact pow_mem (primeShift_mem_finiteToeplitzAlgebra hS p) _

/-- The adjoint `V_m*` of every semigroup shift also belongs to the finite Toeplitz algebra. -/
theorem shiftAdjoint_mem_finiteToeplitzAlgebra
    {S : Finset ℕ} (hS : ∀ p ∈ S, Nat.Prime p)
    (m : finitePrimeSemigroup S) :
    shiftAdjoint hS m ∈ finiteToeplitzAlgebra hS := by
  have hm := star_mem (shiftOperator_mem_finiteToeplitzAlgebra hS m)
  simpa [shiftAdjoint, ContinuousLinearMap.star_eq_adjoint] using hm

/-- The identity operator belongs to the finite Toeplitz algebra. -/
theorem one_mem_finiteToeplitzAlgebra
    {S : Finset ℕ} (hS : ∀ p ∈ S, Nat.Prime p) :
    (1 : FiniteOperator S) ∈ finiteToeplitzAlgebra hS := by
  exact one_mem _

end

end BostConnes
end BrickPileLean
