import BrickPileLean.BostConnes.ExponentVectorPartition
import Mathlib.Data.Nat.Factorization.Basic

namespace BrickPileLean
namespace BostConnes

open scoped BigOperators

noncomputable section

/-- The positive integer encoded by a finite prime exponent vector. -/
def semigroupElement (S : Finset ℕ) (k : ExponentVector S) : ℕ :=
  ∏ p : S, p.1 ^ k p

@[simp] theorem semigroupElement_zero (S : Finset ℕ) :
    semigroupElement S 0 = 1 := by
  simp [semigroupElement]

/-- Addition of exponent vectors corresponds to multiplication of encoded integers. -/
theorem semigroupElement_add (S : Finset ℕ) (k l : ExponentVector S) :
    semigroupElement S (k + l) = semigroupElement S k * semigroupElement S l := by
  simp [semigroupElement, pow_add, Finset.prod_mul_distrib]

private theorem semigroupElement_ne_zero
    {S : Finset ℕ} (hS : ∀ p ∈ S, Nat.Prime p) (k : ExponentVector S) :
    semigroupElement S k ≠ 0 := by
  unfold semigroupElement
  exact Finset.prod_ne_zero fun p _ ↦ pow_ne_zero _ (hS p.1 p.2).ne_zero

/-- Prime factorization recovers each coordinate of an exponent vector. -/
theorem semigroupElement_factorization
    {S : Finset ℕ} (hS : ∀ p ∈ S, Nat.Prime p)
    (k : ExponentVector S) (p : S) :
    (semigroupElement S k).factorization p.1 = k p := by
  classical
  unfold semigroupElement
  rw [Nat.factorization_prod_apply]
  · simp [Nat.factorization_pow, Nat.Prime.factorization,
      fun q : S ↦ hS q.1 q.2, Finsupp.single_apply]
  · intro q _
    exact pow_ne_zero _ (hS q.1 q.2).ne_zero

/-- Unique factorization makes the exponent-vector encoding injective. -/
theorem semigroupElement_injective
    {S : Finset ℕ} (hS : ∀ p ∈ S, Nat.Prime p) :
    Function.Injective (semigroupElement S) := by
  intro k l hkl
  funext p
  rw [← semigroupElement_factorization hS k p,
      ← semigroupElement_factorization hS l p,
      hkl]

/-- The multiplicative semigroup generated by a finite set of primes. -/
def finitePrimeSemigroup (S : Finset ℕ) : Submonoid ℕ where
  carrier := Set.range (semigroupElement S)
  one_mem' := ⟨0, semigroupElement_zero S⟩
  mul_mem' := by
    rintro _ _ ⟨k, rfl⟩ ⟨l, rfl⟩
    exact ⟨k + l, semigroupElement_add S k l⟩

@[simp] theorem mem_finitePrimeSemigroup_iff
    {S : Finset ℕ} {n : ℕ} :
    n ∈ finitePrimeSemigroup S ↔ ∃ k : ExponentVector S, semigroupElement S k = n :=
  Iff.rfl

/-- For a finite prime set, exponent vectors are canonically equivalent to `Λ_S`. -/
def exponentVectorEquivFinitePrimeSemigroup
    (S : Finset ℕ) (hS : ∀ p ∈ S, Nat.Prime p) :
    ExponentVector S ≃ finitePrimeSemigroup S where
  toFun k := ⟨semigroupElement S k, ⟨k, rfl⟩⟩
  invFun n := Classical.choose n.2
  left_inv k := by
    apply semigroupElement_injective hS
    exact Classical.choose_spec ((show (semigroupElement S k) ∈ finitePrimeSemigroup S from ⟨k, rfl⟩))
  right_inv n := by
    apply Subtype.ext
    exact Classical.choose_spec n.2

@[simp] theorem exponentVectorEquivFinitePrimeSemigroup_apply
    (S : Finset ℕ) (hS : ∀ p ∈ S, Nat.Prime p) (k : ExponentVector S) :
    (exponentVectorEquivFinitePrimeSemigroup S hS k : ℕ) = semigroupElement S k :=
  rfl

end

end BostConnes
end BrickPileLean
